import test from 'node:test';
import assert from 'node:assert/strict';
import {WebSocket} from 'ws';
import {once} from 'node:events';
import {setTimeout as delay} from 'node:timers/promises';
import {Match} from '../games/freight-fire/sim.js';
import {validateRoomConfig} from '../games/freight-fire/room-rules.js';
import {startRacingServer} from '../scripts/racing-server.mjs';
async function peer(base){const socket=new WebSocket(base.replace('http:','ws:')+'/fps',{origin:base}),queue=[];socket.on('message',b=>queue.push(JSON.parse(b)));await once(socket,'open');return{socket,send:m=>socket.send(JSON.stringify(m)),async next(type){for(let i=0;i<400;i++){const at=queue.findIndex(m=>typeof type==='function'?type(m):m.type===type);if(at>=0)return queue.splice(at,1)[0];await delay(5);}throw Error('No message '+type);}};}
async function service(t){const app=await startRacingServer({port:0,serveLab:true});t.after(()=>app.close());return{app,base:'http://127.0.0.1:'+app.server.address().port};}
test('front-end and simulation enforce 1..8 teams, fixed AI and at least one human seat',()=>{
 for(let size=1;size<=8;size++)for(const aiCount of [0,size*2-1]){const config=validateRoomConfig({size,aiCount}),m=new Match(config);assert.equal(m.players.length,size*2);assert.equal(m.snapshot().players.length,aiCount);const host=m.addHuman('Host');assert.ok(host);assert.equal(m.snapshot().players.filter(p=>p.bot).length,aiCount);m.restart();assert.equal(m.snapshot().players.filter(p=>p.bot).length,aiCount);m.removeHuman(host.id);assert.equal(m.snapshot().players.length,aiCount);}
 for(const config of [{size:0},{size:9},{size:1.5},{size:1,aiCount:2},{size:8,aiCount:16},{size:4,aiCount:-1},{size:4,aiCount:1.5}])assert.throws(()=>validateRoomConfig(config));
});
test('server accepts every team size, rejects forged boundaries, and never converts human vacancies to AI',async t=>{
 const {app,base}=await service(t);
 for(let size=1;size<=8;size++){const p=await peer(base);p.send({type:'create_room',size,aiCount:0});const joined=await p.next('joined');assert.equal(joined.capacity,size*2);assert.equal(joined.humanCapacity,size*2);assert.equal(joined.snapshot.players.length,1);assert.equal(joined.snapshot.aiCount,0);p.send({type:'leave'});await p.next('left');assert.equal(app.fps.rooms.size,0);p.socket.terminate();}
 for(const config of [{size:0},{size:9},{size:2.5},{size:1,aiCount:2},{size:8,aiCount:16},{size:4,aiCount:-1},{size:4,aiCount:1.5}]){const p=await peer(base);p.send({type:'create_room',...config});assert.equal((await p.next('error')).code,'INVALID_ROOM');p.socket.terminate();}
});
test('true 1v1 zero AI supports full/duplicate checks, host transfer, restart and reconnect identity',async t=>{
 const {app,base}=await service(t),host=await peer(base);host.send({type:'create_room',size:1,aiCount:0,name:'Host'});const h=await host.next('joined'),friend=await peer(base);friend.send({type:'join_room',roomId:h.roomId,name:'Friend'});const f=await friend.next('joined'),room=app.fps.rooms.get(h.roomId);assert.equal(room.match.snapshot().players.length,2);assert.equal(room.match.snapshot().players.filter(p=>p.bot).length,0);assert.deepEqual(room.match.players.map(p=>p.team),[0,1]);
 friend.send({type:'join_room',roomId:h.roomId});assert.equal((await friend.next('error')).code,'ALREADY_JOINED');const extra=await peer(base);extra.send({type:'join_room',roomId:h.roomId});assert.equal((await extra.next('error')).code,'ROOM_FULL');extra.send({type:'join_room',roomId:h.roomId,reconnectToken:f.reconnectToken});assert.equal((await extra.next('error')).code,'ALREADY_CONNECTED');friend.send({type:'restart'});assert.equal((await friend.next('error')).code,'HOST_ONLY');
 host.socket.terminate();for(let i=0;i<100&&room.members.size!==1;i++)await delay(5);assert.equal(room.hostId,f.playerId);assert.equal(room.match.snapshot().aiCount,0);assert.equal(room.match.snapshot().players.find(p=>p.id===h.playerId).connected,false);friend.send({type:'restart'});await friend.next(m=>m.type==='snapshot'&&m.snapshot.time<.05);assert.equal(room.match.snapshot().aiCount,0);
 const resumed=await peer(base);resumed.send({type:'join_room',roomId:h.roomId,reconnectToken:h.reconnectToken});const again=await resumed.next('joined');assert.equal(again.playerId,h.playerId);assert.equal(again.hostId,f.playerId);assert.equal(room.members.size,2);assert.equal(room.match.snapshot().aiCount,0);assert.equal(room.match.snapshot().players.length,2);assert.doesNotMatch(JSON.stringify(await(await fetch(base+'/api/fps/rooms')).json()),/reconnectToken/);
 resumed.send({type:'leave'});await resumed.next('left');friend.send({type:'leave'});await friend.next('left');assert.equal(app.fps.rooms.size,0);resumed.socket.terminate();friend.socket.terminate();extra.socket.terminate();
});
test('expired disconnected seats become vacancies without AI and cannot reuse their token',async t=>{
 const app=await startRacingServer({port:0,serveLab:true});t.after(()=>app.close());const base='http://127.0.0.1:'+app.server.address().port,p=await peer(base);p.send({type:'create_room',size:1,aiCount:0});const h=await p.next('joined'),q=await peer(base);q.send({type:'join_room',roomId:h.roomId});await q.next('joined');const room=app.fps.rooms.get(h.roomId);p.socket.terminate();for(let i=0;i<100&&room.members.size!==1;i++)await delay(5);room.sessions.get(h.reconnectToken).expiresAt=performance.now()-1;await delay(40);assert.equal(room.sessions.size,1);assert.equal(room.match.snapshot().players.length,1);assert.equal(room.match.snapshot().aiCount,0);const r=await peer(base);r.send({type:'join_room',roomId:h.roomId,reconnectToken:h.reconnectToken});assert.equal((await r.next('error')).code,'INVALID_RECONNECT');r.send({type:'join_room',roomId:h.roomId});await r.next('joined');assert.equal(room.match.snapshot().players.length,2);r.socket.terminate();q.socket.terminate();
});

test('two FPS rooms keep same-numbered player slots, inputs and restarts isolated',async t=>{const {app,base}=await service(t),a=await peer(base),b=await peer(base);a.send({type:'create_room',size:1,aiCount:0});b.send({type:'create_room',size:2,aiCount:2});const aj=await a.next('joined'),bj=await b.next('joined'),ra=app.fps.rooms.get(aj.roomId),rb=app.fps.rooms.get(bj.roomId),bp=rb.match.players.find(p=>p.id===bj.playerId),before={x:bp.x,z:bp.z};assert.equal(aj.playerId,bj.playerId);a.send({type:'input',input:{forward:1,yaw:.5,pitch:0}});await delay(180);assert.deepEqual({x:bp.x,z:bp.z},before);assert.ok(ra.match.players.find(p=>p.id===aj.playerId).moving);b.send({type:'restart'});await b.next(m=>m.type==='snapshot'&&m.snapshot.time<.05);assert.ok(ra.match.time>.1);assert.equal(ra.match.snapshot().aiCount,0);assert.equal(rb.match.snapshot().aiCount,2);a.send({type:'leave'});b.send({type:'leave'});await a.next('left');await b.next('left');a.socket.terminate();b.socket.terminate();});
