import test from 'node:test';import assert from 'node:assert/strict';import {Race,sanitizeInput,teamScores} from '../games/apex-rush/sim.js';import {nearest,makeTrack} from '../games/apex-rush/tracks.js';
test('both courses: sixteen AI finish actual laps without resets',()=>{for(const track of ['beach','city']){const r=new Race({track,count:16,laps:2});r.start();for(let i=0;i<12000&&r.status!=='ended';i++)r.tick();assert.equal(r.status,'ended');assert.equal(r.finishOrder.length,16);for(const p of r.players){assert.ok(p.finish>0);assert.equal(p.resets,0);assert.ok(p.progress>=r.track.length*2);}}});
test('human car starts after countdown, accelerates, brakes, and uses a real nitro',()=>{const r=new Race({count:2}),p=r.addHuman('driver');r.start();r.setInput(p.id,{throttle:1});for(let i=0;i<120;i++)r.tick();assert.equal(p.speed,0);for(let i=0;i<200;i++){r.setInput(p.id,{...r.aiInput(p),boost:false});r.tick();}assert.ok(p.speed>30);const speed=p.speed;r.setInput(p.id,{throttle:1,boost:true});r.tick();assert.equal(p.nitro,0);assert.ok(p.boostTime>2);for(let i=0;i<15;i++){r.setInput(p.id,{...r.aiInput(p),boost:true});r.tick();}assert.equal(p.nitro,0);assert.ok(p.speed>speed);r.setInput(p.id,{brake:true});for(let i=0;i<100;i++)r.tick();assert.ok(p.speed<5);});
test('drift generates energy and release offers a mini boost',()=>{const r=new Race({track:'city',count:2}),p=r.addHuman('drifter');r.start();for(let i=0;i<450;i++){const input=r.aiInput(p);r.setInput(p.id,input);r.tick();}let drifted=false,gained=false,mini=false;for(let i=0;i<6000;i++){const input=r.aiInput(p);r.setInput(p.id,input);r.tick();drifted||=p.drifting;gained||=p.energy>.2;mini||=p.miniReady>0;}assert.ok(drifted&&gained&&mini);});
test('reverse and wall bumps cannot award a lap; reset preserves progress',()=>{const r=new Race({count:2}),p=r.addHuman('driver');r.start();for(let i=0;i<190;i++)r.tick();r.setInput(p.id,{throttle:-1,steer:1,drift:true});for(let i=0;i<600;i++)r.tick();assert.equal(p.lap,1);assert.equal(p.finish,null);const progress=p.progress;r.reset(p);assert.equal(p.progress,progress);assert.ok(nearest(r.track,p.x,p.z).distance<2);});
test('human slots replace bots and return to bots without removing cars',()=>{const r=new Race({count:16,mode:'team'}),humans=[];for(let i=0;i<16;i++)humans.push(r.addHuman('h'+i));assert.equal(r.addHuman(),null);assert.equal(r.players.filter(p=>!p.bot).length,16);r.removeHuman(humans[4].id);assert.equal(r.players.length,16);assert.equal(r.players.filter(p=>p.bot).length,1);assert.equal(r.addHuman('replacement').id,humans[4].id);});
test('inputs are finite and capped; fresh restart clears race state',()=>{const i=sanitizeInput({throttle:Infinity,steer:'garbage',boost:true});assert.equal(i.throttle,1);assert.equal(i.steer,0);const r=new Race({count:2}),p=r.addHuman('same');r.start();for(let i=0;i<400;i++)r.tick();p.nitro=0;r.restart();assert.equal(r.status,'countdown');assert.equal(r.time,-3);assert.equal(p.nitro,1);assert.equal(p.name,'same');assert.equal(p.bot,false);});
test('team scoring counts finish order and unfinished racers score zero',()=>{const r=new Race({count:4,mode:'team'});r.players[0].finish=30;r.players[1].finish=31;const s=r.snapshot();assert.deepEqual(teamScores(s),[25,20]);});
test('each track is a closed continuous road with stable projections',()=>{for(const id of ['beach','city']){const t=makeTrack(id);assert.ok(t.length>1000);for(let i=0;i<t.samples.length;i+=10){const p=t.samples[i],n=nearest(t,p.x,p.z);assert.ok(n.distance<.01);assert.ok(Number.isFinite(p.y)&&Number.isFinite(p.h));}}});

test('coastal ramp launches cars and landing returns them to the road',()=>{const r=new Race({track:'beach',count:4,laps:1});r.start();let sawAir=false;for(let i=0;i<2400&&r.status!=='ended';i++){r.tick();for(const p of r.players){if(p.airborne)sawAir=true;assert.ok(p.y>=nearest(r.track,p.x,p.z,p.index).y-.01);}}assert.ok(sawAir);for(const p of r.players){assert.equal(p.airCount,1);assert.equal(p.airborne,false);}});
