import test from 'node:test';import assert from 'node:assert/strict';import {WebSocket} from 'ws';import {startRacingServer,resolveRacingFile} from '../scripts/racing-server.mjs';
const wait=(ms)=>new Promise(r=>setTimeout(r,ms));
async function client(base){const s=new WebSocket(base.replace('http:','ws:')+'/racing',{origin:base}),messages=[];s.on('message',raw=>messages.push(JSON.parse(raw)));await new Promise((r,j)=>{s.once('open',r);s.once('error',j);});return {s,messages,send:m=>s.send(JSON.stringify(m)),next:async type=>{for(let i=0;i<200;i++){const j=messages.findIndex(m=>m.type===type);if(j>=0)return messages.splice(j,1)[0];await wait(10);}throw Error('Missing '+type);}};}
test('authoritative LAN: 16 clients, capacity, real input, host access, AI replacement and host transfer',async()=>{const a=await startRacingServer({port:0,host:'127.0.0.1'}),base='http://127.0.0.1:'+a.server.address().port,clients=[];try{const c=await client(base);clients.push(c);c.send({type:'create',count:16,mode:'team',track:'city',laps:1,name:'Host'});const joined=await c.next('joined'),id=joined.roomId;assert.equal(joined.snapshot.players.length,16);assert.equal(joined.snapshot.status,'grid');
 for(let i=1;i<16;i++){const n=await client(base);clients.push(n);n.send({type:'join',roomId:id,name:'Friend '+i});await n.next('joined');}const room=a.rooms.get(id);assert.equal(room.members.size,16);assert.equal(room.race.players.filter(p=>!p.bot).length,16);
 const extra=await client(base);clients.push(extra);extra.send({type:'join',roomId:id,name:'17th'});assert.match((await extra.next('error')).message,/已满/);
 clients[1].send({type:'start'});assert.match((await clients[1].next('error')).message,/房主/);assert.equal(room.race.status,'grid');c.send({type:'start'});await wait(3200);assert.equal(room.race.status,'racing');c.send({type:'input',input:{throttle:1,boost:true}});await wait(400);const p=room.race.players.find(p=>p.id===joined.playerId);assert.ok(p.speed>5);await wait(900);assert.equal(p.input.throttle,0);
 clients[2].s.close();await wait(150);assert.equal(room.race.players.filter(p=>p.bot).length,1);extra.send({type:'join',roomId:id,name:'Replacement'});await extra.next('joined');assert.equal(room.members.size,16);
 c.s.close();await wait(150);assert.notEqual(room.hostId,joined.playerId);assert.equal(room.race.players.filter(p=>p.bot).length,1);
 assert.equal((await fetch(base+'/api/racing/health')).status,200);assert.equal((await fetch(base+'/games/apex-rush/')).status,200);assert.equal((await fetch(base+'/package.json')).status,404);
 }finally{for(const c of clients)c.s.terminate();await a.close();}});
test('unsafe paths and cross-origin sockets are rejected',async()=>{for(const p of ['/package.json','/games/apex-rush/../freight-fire/index.html','/games/apex-rush/%2e%2e/scripts/serve.mjs','/games/apex-rush/%5cfoo','/games/apex-rush/.env'])assert.equal(resolveRacingFile('D:/ChatGPTProject/ai-game-lab',p),null);const a=await startRacingServer({port:0,host:'127.0.0.1'});try{const s=new WebSocket('ws://127.0.0.1:'+a.server.address().port+'/racing',{origin:'https://unrelated.invalid'});const code=await new Promise(resolve=>s.on('unexpected-response',(req,res)=>{resolve(res.statusCode);res.destroy();}));assert.equal(code,403);}finally{await a.close();}});
