export class RaceAudio{
 constructor(){this.enabled=true;}
 async start(){if(!this.context){const A=window.AudioContext||window.webkitAudioContext;if(!A)return;this.context=new A();this.master=this.context.createGain();this.master.gain.value=this.enabled?.16:0;this.master.connect(this.context.destination);this.engine=this.context.createOscillator();this.engine.type='sawtooth';this.filter=this.context.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=360;this.motorGain=this.context.createGain();this.motorGain.gain.value=.10;this.engine.connect(this.filter);this.filter.connect(this.motorGain);this.motorGain.connect(this.master);this.engine.start();const length=this.context.sampleRate*2,b=this.context.createBuffer(1,length,this.context.sampleRate),a=b.getChannelData(0);for(let i=0;i<length;i++)a[i]=Math.random()*2-1;this.noise=this.context.createBufferSource();this.noise.buffer=b;this.noise.loop=true;this.noiseFilter=this.context.createBiquadFilter();this.noiseFilter.type='highpass';this.noiseFilter.frequency.value=1500;this.noiseGain=this.context.createGain();this.noiseGain.gain.value=0;this.noise.connect(this.noiseFilter);this.noiseFilter.connect(this.noiseGain);this.noiseGain.connect(this.master);this.noise.start();}await this.context.resume();}
 setEnabled(on){this.enabled=on;if(this.master)this.master.gain.setTargetAtTime(on?.16:0,this.context.currentTime,.1);}
 update(p,running){if(!this.context)return;const t=this.context.currentTime,gear=Math.floor(p.speed/13);this.engine.frequency.setTargetAtTime(running?52+(p.speed%13)*5+gear*10:37,t,.07);this.filter.frequency.setTargetAtTime(300+p.speed*9,t,.1);this.motorGain.gain.setTargetAtTime(running?.11:0,t,.15);this.noiseGain.gain.setTargetAtTime(!running?0:p.drifting?.095:p.boostTime>0?.05:p.speed*.00035,t,.08);}
 beep(high=false){if(!this.context)return;const o=this.context.createOscillator(),g=this.context.createGain(),t=this.context.currentTime;o.type='sine';o.frequency.value=high?880:440;g.gain.setValueAtTime(.28,t);g.gain.exponentialRampToValueAtTime(.001,t+.22);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+.23);}
 dispose(){this.stop();this.context?.close().catch(()=>{});this.context=null;}
 stop(){if(this.context){this.motorGain.gain.value=0;this.noiseGain.gain.value=0;}}
}
