import {Race,COLORS,formatTime,teamScores} from './sim.js';
import {makeTrack,TRACKS,angle} from './tracks.js';
import {RaceView} from './render.js';
import {RaceAudio} from './audio.js';
import {RaceNetwork} from './network.js';
import {createLanLobby,isLanHost} from './lan.js';
import {ONLINE_GAME_URL,remainingTime} from './config.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const keys=new Set(),touch=new Set(),audio=new RaceAudio();
let view,race,snapshot,localId,trackId='beach',colorIndex=0,mode='offline',phase='menu',paused=false,net=null,room=null,last=performance.now(),accumulator=0,sendTime=0,roomClockOffset=0,lastCountdown='',lastResult='',toastTimeout,visible=true,eventUntil=0,lastNitro=1,previousModalFocus,raceEpoch=null;
let boostTap=false,resetTap=false;
const isTouch=matchMedia('(pointer: coarse)').matches||navigator.maxTouchPoints>0;
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('#toast').hidden=true,5000);}
const lanLobby=createLanLobby({join:code=>{$('#room-code').value=code;connectRoom(false);},notice:toast,isMenu:()=>phase==='menu'});
function modal(id,open){const e=$('#'+id);e.hidden=!open;if(open){previousModalFocus=document.activeElement;(e.querySelector('button')||e).focus();}else previousModalFocus?.focus?.();}
function settings(){return {track:trackId,count:Number($('#count').value),mode:$('#race-mode').value,laps:Number($('#laps').value),difficulty:$('#difficulty').value,assist:$('#assist').checked};}
function person(){return snapshot?.players.find(p=>p.id===localId);}
function buildPreview(){race=new Race({...settings(),count:2});const p=race.addHuman($('#nickname').value,colorIndex);localId=p.id;snapshot=race.snapshot();view.load(race.track);view.camReady=false;$('#showcase-name').textContent=race.track.name;$('#showcase-sub').textContent=race.track.subtitle;$('#showcase-spec').textContent=trackId==='beach'?'宽阔海岸 · 连续 S 弯 · 起伏路段':'海上城池 · 连续发卡 · 欧式街区';$('.track-weather').textContent=trackId==='beach'?'24° / 晴 · 海风 3级':'19° / 晴 · 城市漫游';}
function enterRace(){lanLobby.stop();phase='race';paused=false;boostTap=false;resetTap=false;keys.clear();touch.clear();$('#app').classList.add('racing');$('#hud').hidden=false;$('#room-panel').hidden=true;$('#touch-controls').hidden=!isTouch;$('#results').hidden=true;$('#pause').hidden=true;view.camReady=false;lastCountdown='';lastResult='';lastNitro=person()?.nitro||1;audio.start().catch(()=>{});$('#scene').focus?.();}
function goMenu(){net?.close();net=null;room=null;raceEpoch=null;phase='menu';paused=false;keys.clear();touch.clear();$('#app').classList.remove('racing');for(const id of ['hud','touch-controls','pause','results','room-panel'])$('#'+id).hidden=true;$('#menu').hidden=false;audio.stop();buildPreview();lanLobby.setActive(mode==='offline'?false:mode);$(mode==='offline'?'#start':'#create-room').focus();}
function startLocal(){net?.close();net=null;room=null;race=new Race(settings());const p=race.addHuman($('#nickname').value,colorIndex);localId=p.id;view.load(race.track);race.start();snapshot=race.snapshot();enterRace();}
function setMode(m){if(m==='online'&&!isLanHost(location.hostname)&&location.origin!==new URL(ONLINE_GAME_URL).origin){const target=new URL(ONLINE_GAME_URL);target.search=location.search;target.searchParams.set('online','1');location.assign(target.href);return;}mode=m;$$('[data-mode]').forEach(b=>{const a=b.dataset.mode===m;b.classList.toggle('active',a);b.setAttribute('aria-pressed',a);});$('#offline-actions').hidden=m!=='offline';$('#lan-actions').hidden=m==='offline';lanLobby.setActive(m==='offline'?false:m);}
function setTrack(id){trackId=id;$$('[data-track]').forEach(b=>{const a=b.dataset.track===id;b.classList.toggle('active',a);b.setAttribute('aria-pressed',a);});if(phase==='menu'&&!room)buildPreview();}
function input(){return {throttle:keys.has('KeyW')||keys.has('ArrowUp')||touch.has('gas')?1:keys.has('KeyS')||keys.has('ArrowDown')?-1:0,steer:(keys.has('KeyD')||keys.has('ArrowRight')||touch.has('right')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')||touch.has('left')?1:0),drift:keys.has('ShiftLeft')||keys.has('ShiftRight')||touch.has('drift'),boost:boostTap||keys.has('Space')||keys.has('ControlLeft')||keys.has('ControlRight')||touch.has('boost'),brake:keys.has('KeyS')||keys.has('ArrowDown')||touch.has('brake'),reset:resetTap||keys.has('KeyR')};}
function pauseToggle(){if(phase!=='race'||person()?.finish!==null)return;paused=!paused;boostTap=false;resetTap=false;keys.clear();touch.clear();modal('pause',paused);$('#pause-description').textContent=net?'你已松开油门。联机比赛仍在继续。':'比赛已暂停，准备好再出发。';$('#restart').disabled=!!net&&room?.hostId!==localId;}
function renderRoom(){
 if(!room)return;$('#menu').hidden=true;$('#room-panel').hidden=false;const host=room.hostId===localId;
 $('#room-info').textContent=room.humanCount+' 位好友 / '+room.count+' 辆赛车 · '+(room.mode==='team'?'红蓝组队':'个人竞速')+' · '+room.laps+' 圈'+(host?' · 你是房主':'');
 $('#room-roster').replaceChildren(...room.players.map(p=>{const e=document.createElement('div');e.className='roster-player';const i=document.createElement('i');i.style.background=room.mode==='team'?(p.team===0?'#ef6953':'#31a6d4'):p.color;const name=document.createElement('span');name.textContent=p.name;const type=document.createElement('small');type.textContent=p.bot?'AI':p.id===room.hostId?'房主':'好友';e.append(i,name,type);return e;}));
 $('#room-start').hidden=!host;$('#invite-hint').textContent=host?'把邀请链接发给好友；AI 自动补齐空位。':'等待房主发车。未满的位置由 AI 补齐。';
 let sw=$('#switch-team');if(!sw){sw=document.createElement('button');sw.id='switch-team';sw.textContent='切换红蓝队';sw.style.cssText='background:#e3eef0;color:#123f54;padding:7px;font-size:11px;border-radius:4px;margin:4px 0';$('#room-info').after(sw);sw.onclick=()=>{const p=room.players.find(p=>p.id===localId);net?.send({type:'team',team:p.team===0?1:0});};}sw.hidden=room.mode!=='team';
}
async function connectRoom(create){
 if(net)net.close();const n=new RaceNetwork(m=>{
  if(m.type==='error'){toast(m.message);return;}
  if(m.type==='room-expired'){goMenu();toast(m.message);return;}
  if(m.type==='joined'){roomClockOffset=(m.serverNow||Date.now())-Date.now();raceEpoch=m.epoch??null;room={...m};snapshot=m.snapshot;localId=m.playerId;trackId=snapshot.track;view.load(makeTrack(trackId));phase='room';lanLobby.stop();$('#menu').hidden=true;$('#room-panel').hidden=false;const publicInvite=m.online?m.invites[0]||m.local:location.hostname==='localhost'||location.hostname.startsWith('127.')?m.invites[0]||m.local:location.origin+location.pathname+'?lan=1&room='+m.roomId;$('#invite-link').value=publicInvite;toast(m.invites.length?'房间已就绪，可以邀请好友。':'房间已就绪；尚未检测到内网地址，请确认 Wi-Fi 连接。');}
  if(m.type==='room'){roomClockOffset=(m.serverNow||Date.now())-Date.now();room={...room,...m};if(phase==='room')renderRoom();}
  if(m.type==='snapshot'){const newRace=Number.isFinite(m.epoch)&&raceEpoch!==null&&m.epoch!==raceEpoch;raceEpoch=m.epoch??raceEpoch;snapshot=m.snapshot;if(['countdown','racing'].includes(snapshot.status)&&(phase==='room'||newRace))enterRace();if(phase==='race'&&snapshot.status==='grid'){phase='room';$('#app').classList.remove('racing');$('#hud').hidden=true;renderRoom();}}
 },()=>{if(net===n){goMenu();toast('与主机的连接已断开，请重新加入房间。');}});
 net=n;try{await n.connect();const data={name:$('#nickname').value,color:colorIndex};if(create)n.send({type:'create',...settings(),...data});else{let code=$('#room-code').value.trim();try{code=new URL(code).searchParams.get('room')||code;}catch{}if(!/^[A-Za-z0-9_-]{12}$/.test(code))throw Error('请输入有效的12位房间码或完整邀请链接');n.send({type:'join',roomId:code,...data});}}catch(e){n.close();if(net===n)net=null;toast(e.message);}
}
function drawTrackCards(){for(const b of $$('[data-track]')){const t=makeTrack(b.dataset.track),a=t.samples,xs=a.map(p=>p.x),zs=a.map(p=>p.z),xmin=Math.min(...xs),zmin=Math.min(...zs),scale=Math.min(90/(Math.max(...xs)-xmin),60/(Math.max(...zs)-zmin)),d=a.filter((p,i)=>i%3===0).map((p,i)=>(i?'L':'M')+(10+(p.x-xmin)*scale).toFixed(1)+','+(8+(p.z-zmin)*scale).toFixed(1)).join(' ')+'Z';b.querySelector('svg').innerHTML='<path d="'+d+'" fill="none" stroke="#d6e9ec" stroke-width="7" stroke-linejoin="round"/><path d="'+d+'" fill="none" stroke="'+(b.dataset.track==='beach'?'#19a8b8':'#5c8395')+'" stroke-width="2" stroke-linejoin="round"/>';} }
function drawMap(){
 const c=$('#minimap'),ctx=c.getContext('2d'),t=view.track,a=t.samples,xs=a.map(p=>p.x),zs=a.map(p=>p.z),minX=Math.min(...xs),minZ=Math.min(...zs),scale=Math.min(204/(Math.max(...xs)-minX),162/(Math.max(...zs)-minZ)),px=x=>18+(x-minX)*scale,pz=z=>18+(z-minZ)*scale;ctx.clearRect(0,0,240,200);ctx.lineWidth=7;ctx.strokeStyle='#e7f8fc';ctx.lineJoin='round';ctx.beginPath();for(let i=0;i<a.length;i+=3){const p=a[i];if(i===0)ctx.moveTo(px(p.x),pz(p.z));else ctx.lineTo(px(p.x),pz(p.z));}ctx.closePath();ctx.stroke();for(const p of snapshot.players){ctx.beginPath();ctx.fillStyle=p.id===localId?'#ffcd50':snapshot.mode==='team'?(p.team===0?'#ff765b':'#53bdf7'):p.color;ctx.arc(px(p.x),pz(p.z),p.id===localId?5:3,0,Math.PI*2);ctx.fill();if(p.id===localId){ctx.strokeStyle='#ffffff';ctx.lineWidth=2;ctx.stroke();}}$('#team-score').textContent=snapshot.mode==='team'?'红队 '+teamScores(snapshot)[0]+' : '+teamScores(snapshot)[1]+' 蓝队':'';
}
let hudClock=0;
function hud(dt){
 const p=person();if(!p)return;hudClock+=dt;const order=snapshot.order,rank=order.indexOf(localId)+1;$('#place').textContent=String(rank).padStart(2,'0');$('#total').textContent=String(snapshot.count).padStart(2,'0');$('#track-name').textContent=view.track.name;$('#lap').textContent=p.lap;$('#lap-total').textContent=snapshot.laps;$('#race-time').textContent=formatTime(p.finish??snapshot.time);$('#speed').textContent=String(Math.round(p.speed*3.6)).padStart(3,'0');$('#gear').textContent=Math.min(6,1+Math.floor(p.speed/13))+' GEAR';$('#energy-fill').style.width=p.energy*100+'%';$('#nitro-tanks').querySelectorAll('i').forEach((e,j)=>e.classList.toggle('full',j<p.nitro));
 $('#drive-state').textContent=p.boostTime>0?'N₂O / 氮气加速':p.miniTime>0?'BOOST / 出弯喷射':p.airborne?'AIR / 腾空':p.drifting?'DRIFT / 漂移集气':'GRIP / 抓地';$('#mini-tip').textContent=p.miniReady>0?'现在按 Space：出弯续喷':p.collision>0?'轻碰护栏 · 调整方向':p.drifting?'稳住方向，松开 Shift 出弯':'Shift + 方向键漂移集气';$('#boost-flash').style.opacity=(p.boostTime>0||p.miniTime>0)&&!view.reduce?'1':'0';
 let cd=snapshot.time<0?String(Math.ceil(-snapshot.time)):snapshot.time<.7?'GO!':'';$('#countdown').textContent=cd;if(cd&&cd!==lastCountdown)audio.beep(cd==='GO!');lastCountdown=cd;
 if(p.nitro>lastNitro){eventUntil=performance.now()+1100;$('#race-event').textContent='N₂O READY / 氮气就绪';}lastNitro=p.nitro;if(p.finish!==null&&snapshot.status!=='ended')$('#race-event').textContent='已冲线 · 等待其他车手';else if(performance.now()>eventUntil)$('#race-event').textContent='';
 if(hudClock>.14){hudClock=0;$('#leaders').replaceChildren(...order.slice(0,6).map((id,j)=>{const r=snapshot.players.find(p=>p.id===id),e=document.createElement('li');e.className=id===localId?'me':'';const rank=document.createElement('b');rank.textContent=String(j+1).padStart(2,'0');const dot=document.createElement('i');dot.style.background=snapshot.mode==='team'?(r.team===0?'#ed6e54':'#32bbdf'):r.color;const name=document.createElement('span');name.textContent=r.name;const type=document.createElement('small');type.textContent=r.finish!==null?'✓':r.bot?'AI':'YOU';e.append(rank,dot,name,type);return e;}));drawMap();}
 if(snapshot.status==='ended')showResults();
}
function showResults(){
 const sig=snapshot.order.join(',')+snapshot.status;if(sig===lastResult)return;lastResult=sig;paused=false;$('#pause').hidden=true;$('#touch-controls').hidden=true;modal('results',true);audio.stop();const p=person(),rank=snapshot.order.indexOf(localId)+1,scores=teamScores(snapshot);$('#result-title').textContent=snapshot.mode==='team'?(scores[0]===scores[1]?'势均力敌。':(scores[0]>scores[1]?'红队':'蓝队')+'拿下这一场。'):rank===1?'第一名，漂亮。':'每个弯，都算数。';$('#result-sub').textContent='你的名次 '+rank+' / '+snapshot.count+' · '+(p.finish!==null?'完赛 '+formatTime(p.finish):'未完赛')+(snapshot.mode==='team'?' · 红 '+scores[0]+' : '+scores[1]+' 蓝':'');
 $('#result-table').replaceChildren(...snapshot.order.map((id,i)=>{const p=snapshot.players.find(p=>p.id===id),row=document.createElement('div');row.className='result-row'+(id===localId?' me':'');for(const [tag,text] of [['b',String(i+1).padStart(2,'0')],['span',p.name],['small',snapshot.mode==='team'?(p.team===0?'红队':'蓝队'):p.bot?'AI':'车手'],['b',formatTime(p.finish)]]){const e=document.createElement(tag);e.textContent=text;row.append(e);}return row;}));$('#result-restart').disabled=!!net&&room?.hostId!==localId;
}
function visualSnapshot(){return net?.visualSnapshot()||snapshot;}
function frame(now){
 const dt=Math.min((now-last)/1000,.1);last=now;
 if(visible&&view){if(phase==='race'){
  if(net){sendTime+=dt;if(sendTime>=1/30){net.send({type:'input',input:paused?{}:input()});sendTime%=1/30;boostTap=false;resetTap=false;}}
  else if(!paused){accumulator+=dt;race.setInput(localId,input());while(accumulator>=1/60){race.tick(1/60);boostTap=false;resetTap=false;accumulator-=1/60;}snapshot=race.snapshot();}
  if(!paused||net)view.render(visualSnapshot(dt),localId,dt,false);hud(dt);audio.update(person(),!paused&&snapshot.status==='racing');
 }else{view.render(snapshot,localId,dt,true);audio.stop();}
 $('#performance').textContent=(view.stats.fps||'—')+' FPS / '+(net?(mode==='online'?'ONLINE CONNECTED':'LAN CONNECTED'):'LOCAL RACING');
 }requestAnimationFrame(frame);
}
$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('[data-track]').forEach(b=>b.onclick=()=>setTrack(b.dataset.track));$$('[data-color]').forEach(b=>b.onclick=()=>{colorIndex=Number(b.dataset.color);$$('[data-color]').forEach(e=>e.classList.toggle('selected',e===b));if(phase==='menu'&&!room)buildPreview();});
$('#start').onclick=startLocal;$('#create-room').onclick=()=>connectRoom(true);$('#join-room').onclick=()=>connectRoom(false);$('#leave-room').onclick=goMenu;$('#room-start').onclick=()=>net?.send({type:room?.status==='ended'?'restart':'start'});$('#pause-open').onclick=pauseToggle;$('#resume').onclick=pauseToggle;$('#leave').onclick=goMenu;$('#result-menu').onclick=goMenu;
function restart(){if(net){if(room?.hostId!==localId){toast('等待房主重新发车');return;}keys.clear();touch.clear();net.send({type:'restart'});$('#results').hidden=true;$('#pause').hidden=true;paused=false;lastResult='';lastCountdown='';audio.start().catch(()=>{});$('#touch-controls').hidden=!isTouch;view.camReady=false;}else startLocal();}
$('#restart').onclick=restart;$('#result-restart').onclick=restart;$('#camera').onclick=()=>{view.cameraMode=(view.cameraMode+1)%2;view.camReady=false;};
$('#settings-open').onclick=()=>modal('settings',true);$('#help-open').onclick=()=>modal('help',true);$$('[data-close]').forEach(b=>b.onclick=()=>modal(b.dataset.close,false));
$('#quality').onchange=()=>view?.setQuality($('#quality').value);$('#sound').onchange=()=>audio.setEnabled($('#sound').checked);$('#assist').onchange=()=>{if(race)race.assist=$('#assist').checked;};$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#app').requestFullscreen();}catch{toast('当前浏览器不支持全屏；可使用浏览器的全屏菜单。');}};
$('#copy-invite').onclick=async()=>{const v=$('#invite-link').value;try{await navigator.clipboard.writeText(v);toast('邀请链接已复制');}catch{$('#invite-link').focus();$('#invite-link').select();if(document.execCommand('copy'))toast('邀请链接已复制');else toast('请复制选中的链接发给好友');}};
addEventListener('keydown',e=>{if(e.code==='Escape'){const opened=['settings','help'].find(id=>!$('#'+id).hidden);if(opened){modal(opened,false);return;}}
 if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;
 if(phase==='race'&&['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code))e.preventDefault();
 if(!e.repeat&&['Escape','KeyP'].includes(e.code))pauseToggle();if(phase!=='race'||paused||!$('#results').hidden)return;if(!e.repeat&&e.code==='KeyC')$('#camera').click();if(!e.repeat&&['Space','ControlLeft','ControlRight'].includes(e.code))boostTap=true;if(!e.repeat&&e.code==='KeyR')resetTap=true;keys.add(e.code);
});
addEventListener('keyup',e=>keys.delete(e.code));
function clearInputs(){boostTap=false;resetTap=false;keys.clear();touch.clear();$$('[data-control]').forEach(b=>b.classList.remove('held'));if(net)net.send({type:'input',input:{}});}
addEventListener('blur',()=>{clearInputs();if(phase==='race'&&!net&&!paused)pauseToggle();});
document.addEventListener('visibilitychange',()=>{visible=!document.hidden;clearInputs();if(visible&&net)view.camReady=false;last=performance.now();accumulator=0;if(!visible&&phase==='race'&&!net&&!paused)pauseToggle();});
addEventListener('message',e=>{if(e.source===window.parent&&e.data?.type==='ai-game-lab:pause'){clearInputs();if(phase==='race'&&!net&&!paused)pauseToggle();}});
$$('[data-control]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);touch.add(b.dataset.control);if(b.dataset.control==='boost')boostTap=true;b.classList.add('held');audio.start().catch(()=>{});};const up=()=>{touch.delete(b.dataset.control);b.classList.remove('held');};b.onpointerup=up;b.onpointercancel=up;b.onlostpointercapture=up;});
document.addEventListener('keydown',e=>{if(e.code!=='Tab')return;const dialog=$$('.modal').find(m=>!m.hidden);if(!dialog)return;const items=[...dialog.querySelectorAll('button:not(:disabled),input,select')].filter(e=>e.offsetParent!==null);if(!items.length)return;const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
try{drawTrackCards();view=new RaceView($('#scene'));buildPreview();const code=new URLSearchParams(location.search).get('room');if(new URLSearchParams(location.search).has('online')||code&&!isLanHost(location.hostname))setMode('online');else if(code||new URLSearchParams(location.search).has('lan'))setMode('lan');if(code){$('#room-code').value=code;$('#room-code').closest('details').open=true;toast('好友邀请已填好，输入昵称后点击加入。');}requestAnimationFrame(frame);if(new URLSearchParams(location.search).has('qa'))window.__apex={get race(){return race;},get snapshot(){return snapshot;},get localId(){return localId;},get phase(){return phase;},get paused(){return paused;},get view(){return view;},input,net:()=>net,settings};}
catch(e){$('#fatal').hidden=false;$('#fatal-message').textContent=e.message;console.error(e);}
addEventListener('pagehide',()=>{lanLobby.stop();net?.close();audio.stop();view?.dispose();},{once:true});

setInterval(()=>{const online=!!room?.online,stamp=Date.now()+roomClockOffset;$('#session-expiry').hidden=!online;const text=online?'房间剩余 '+remainingTime(room.expiresAt,stamp)+' · 到期自动关闭':'';$('#session-expiry').textContent=text;$('#room-lifetime').textContent=text;},1000);
